version: 2

models:
  - name: stg_taxi_trips
    description: "Cleaned Silver layer for NYC Yellow Taxi trip records."
    columns:
      - name: vendor_id
        description: "A code indicating the TPEP provider that provided the record."
        tests:
          - not_null
          
      - name: pickup_datetime
        description: "Date and time when the meter was engaged."
        tests:
          - not_null
          
      - name: passenger_count
        description: "The number of passengers in the vehicle."
        tests:
          - not_null
          
      - name: payment_type
        description: "A numeric code signifying how the passenger paid for the trip."
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]